// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetCareHub.Infrastructure.Persistence;

#nullable disable

namespace PetCareHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetCareHubContext))]
    [Migration("20260514005735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCareHub.Domain.Entities.AlertaSaude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RESOLUCAO");

                    b.Property<long?>("LeituraId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    b.Property<decimal?>("LimiteReferencia")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("LIMITE_REFERENCIA");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<string>("NivelAlerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL_ALERTA");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Resolvido")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("RESOLVIDO");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_ALERTA");

                    b.Property<decimal?>("ValorDetectado")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR_DETECTADO");

                    b.HasKey("Id");

                    b.HasIndex("DataAlerta");

                    b.HasIndex("LeituraId");

                    b.HasIndex("NivelAlerta");

                    b.HasIndex("PetId");

                    b.HasIndex("Resolvido");

                    b.ToTable("ALERTA_SAUDE", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClinicaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSULTA");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RETORNO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DIAGNOSTICO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("RetornoRecomendado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("RETORNO_RECOMENDADO");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_CONSULTA");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("DataConsulta");

                    b.HasIndex("PetId");

                    b.ToTable("CONSULTA", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.EventoPreventivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_EVENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PREVISTA");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REALIZACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<long?>("ProtocoloId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROTOCOLO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_EVENTO");

                    b.HasKey("Id");

                    b.HasIndex("DataPrevista");

                    b.HasIndex("PetId");

                    b.HasIndex("Status");

                    b.ToTable("EVENTO_PREVENTIVO", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<long>("DispositivoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_DISPOSITIVO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("StatusLeitura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_LEITURA");

                    b.Property<string>("TipoLeitura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_LEITURA");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("DataLeitura");

                    b.HasIndex("PetId");

                    b.HasIndex("TipoLeitura");

                    b.ToTable("LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<long>("ClinicaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("CondicoesCronicas")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CONDICOES_CRONICAS");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<string>("Raca")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SEXO");

                    b.Property<long>("TutorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TUTOR");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("Especie");

                    b.HasIndex("TutorId");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.ScoreSaude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_SCORE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CALCULO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PET");

                    b.Property<int>("ScoreAlimentacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_ALIMENTACAO");

                    b.Property<int>("ScoreAmbiente")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_AMBIENTE");

                    b.Property<int>("ScoreAtividade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_ATIVIDADE");

                    b.Property<int>("ScoreConsulta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_CONSULTA");

                    b.Property<int>("ScorePreventivo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_PREVENTIVO");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("DataCalculo");

                    b.HasIndex("PetId");

                    b.ToTable("SCORE_SAUDE", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.AlertaSaude", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.LeituraSensor", "LeituraSensor")
                        .WithMany("AlertasSaude")
                        .HasForeignKey("LeituraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("AlertasSaude")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeituraSensor");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Consultas")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.EventoPreventivo", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("EventosPreventivos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("LeiturasSensor")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pets")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.ScoreSaude", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("ScoresSaude")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.Navigation("AlertasSaude");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.Navigation("AlertasSaude");

                    b.Navigation("Consultas");

                    b.Navigation("EventosPreventivos");

                    b.Navigation("LeiturasSensor");

                    b.Navigation("ScoresSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
