// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetCareHub.Infrastructure.Persistence;

#nullable disable

namespace PetCareHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PetCareHubContext))]
    [Migration("20260513013813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCareHub.Domain.Entities.AlertaSaude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_RESOLUCAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long?>("LeituraSensorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LEITURA_SENSOR_ID");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("Resolvido")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESOLVIDO");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_ALERTA");

                    b.HasKey("Id");

                    b.HasIndex("DataAlerta");

                    b.HasIndex("LeituraSensorId");

                    b.HasIndex("Nivel");

                    b.HasIndex("PetId");

                    b.HasIndex("Resolvido");

                    b.ToTable("ALERTA_SAUDE", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Clinica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("CLINICA", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClinicaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CLINICA_ID");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CONSULTA");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("OBSERVACOES");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("RetornoRecomendado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RETORNO_RECOMENDADO");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_CONSULTA");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("DataConsulta");

                    b.HasIndex("PetId");

                    b.ToTable("CONSULTA", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.EventoPreventivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PREVISTA");

                    b.Property<DateTime?>("DataRealizacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_REALIZACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("DataPrevista");

                    b.HasIndex("PetId");

                    b.HasIndex("Status");

                    b.ToTable("EVENTO_PREVENTIVO", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_LEITURA");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<string>("StatusLeitura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS_LEITURA");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO_SENSOR");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("UNIDADE_MEDIDA");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("DECIMAL(10,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("DataLeitura");

                    b.HasIndex("PetId");

                    b.HasIndex("TipoSensor");

                    b.ToTable("LEITURA_SENSOR", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Ativo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ATIVO");

                    b.Property<long>("ClinicaId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CLINICA_ID");

                    b.Property<string>("CondicoesCronicas")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CONDICOES_CRONICAS");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("PESO_KG");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("SEXO");

                    b.Property<long>("TutorId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TUTOR_ID");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("Especie");

                    b.HasIndex("TutorId");

                    b.ToTable("PET", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.ScoreSaude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CATEGORIA");

                    b.Property<DateTime>("DataCalculo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CALCULO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<long>("PetId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PET_ID");

                    b.Property<int>("ScoreTotal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SCORE_TOTAL");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("DataCalculo");

                    b.HasIndex("PetId");

                    b.ToTable("SCORE_SAUDE", (string)null);
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.AlertaSaude", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.LeituraSensor", "LeituraSensor")
                        .WithMany("AlertasSaude")
                        .HasForeignKey("LeituraSensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("AlertasSaude")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeituraSensor");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Consultas")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.EventoPreventivo", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("EventosPreventivos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("LeiturasSensor")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Clinica", "Clinica")
                        .WithMany("Pets")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.ScoreSaude", b =>
                {
                    b.HasOne("PetCareHub.Domain.Entities.Pet", "Pet")
                        .WithMany("ScoresSaude")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Clinica", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.LeituraSensor", b =>
                {
                    b.Navigation("AlertasSaude");
                });

            modelBuilder.Entity("PetCareHub.Domain.Entities.Pet", b =>
                {
                    b.Navigation("AlertasSaude");

                    b.Navigation("Consultas");

                    b.Navigation("EventosPreventivos");

                    b.Navigation("LeiturasSensor");

                    b.Navigation("ScoresSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
